# Application binary target
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary", "kt_jvm_library")

kt_jvm_library(
    name = "app_lib",
    srcs = ["src/main/kotlin/com/example/App.kt", "src/main/kotlin/com/example/health.kt"],
    deps = [],
)

kt_jvm_binary(
    name = "app",
    main_class = "com.example.AppKt",
    runtime_deps = [
        ":app_lib",
    ],
)